---
- name: clone roles
  hosts: all
  become: true
  vars:
    git_repository: https://github.com/Kurdzik/Ansible_roles.git
    git_branch: master 
  tasks:
    - name: create directory
      file:
        path: /etc/ansible/roles
        state: directory
        mode: '0755'
    - name: git checkout
      git:
        repo: "{{ git_repository }}"
        dest: "/etc/ansible/roles"
        version: "{{ git_branch }}"

